[project]
name = "mini-project"
version = "0.1.0"
description = "Tiny demo project with code and docs for GitHub Pages"
requires-python = ">=3.11"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-q"

[dependency-groups]
dev = ["fastapi", "uvicorn", "httpx", "pytest"]
